### ISSUE TITLE
convert backslash to forwardslash in path for target_link_libraries on windows

### ISSUE THREAD

**Issue by fwanggg** [algorys/cmakeconverter#18]
if backslashes are used in "Linker"->"Input"->"Additional Dependencies", e.g.
"$(ProjectDir)\..\release\foo.lib"
they will not be converted to forward slashes after conversion, i.e.

"target_link_libraries(${PROJECT_NAME} $(ProjectDir)..\release\foo.lib)"

 This will cause cmake to have error
"Invalid escape sequence \."

expected behavior: The converter should convert those back slashes to forward slashes.

**Comment by algorys** [comment]
@fwanggg  I'll fix it ASAP.

**Comment by algorys** [comment]
**EDIT:** Strange thing here is that normally you should not have a path to this line. Do you have the vcxproj impacted ? Or the part of the XML that causes this behavior ?

**Comment by fwanggg** [comment]
I've updated my original comment. My example was incorrect. I meant **libraries** not **header files**.

And Sorry i cannot provide the vcxproj that i used to reproduce this issue. Simply 
**"Strange thing here is that normally you should not have a path to this line"**
Yes, you are right. This is sometimes considered anti-pattern to include the path for this option. However, i think in real world, people still do this from time to time due to different reasons. 
My thought is simply that if MSVS can handle this then the converter should handle this too.

**Comment by algorys** [comment]
Ok @fwanggg. I'll manage this possibility :wink:

**Comment by algorys** [comment]
Fixed.
