### ISSUE TITLE
Env variable can not be resolved

### ISSUE THREAD

**Issue by lisnop** [algorys/cmakeconverter#44]
In projects, we define and use a system wise environment variable. But it can not be resolved by cmakeconverter properly.

For example, we define an environment variable CSE_ROOT. In vcxproj file it refers as $(CSE_ROOT) in AdditionalIncludeDirectories. But cmakeconverter can not recognize it during converting.

**Comment by pavelliavonau** [comment]
Can you provide conversion log and result CMakeLists.txt for corresponding project?
Everything is ok on my side and I can't reproduce the error.

**Comment by pavelliavonau** [comment]
No response.
