### ISSUE TITLE
I'm trying to convert a .sln file using "cmake-converter -s *.sln", doesn't work

### ISSUE THREAD

**Issue by kegao1** [algorys/cmakeconverter#46]
I successfully install the cmake-converter. I have a .sln file, which connecting to a series of fortran project. I use "cmake-converter -s *.sln", it doesn't do anything. It seems cmake-converter doesn't have "-s" flag

**Comment by pavelliavonau** [comment]
How have you installed it? You need install from sources from develop branch because last release is too outdated.

**Comment by kegao1** [comment]
Yes, you're right. After installing the source directly, it works. Thanks. Amazing tool!

**Comment by pavelliavonau** [comment]
:blush: thanks. I'm glad
