### ISSUE TITLE
Interpreting path names ending with "\" (in <AdditionalIncludeDirectories> in vcxproject) results in an Error.

### ISSUE THREAD

**Issue by bigla** [algorys/cmakeconverter#55]
When converting a solution file (or a vcxproject file for that matter) paths ending with a `"\"` in `<AdditionalIncludeDirectories>` will lead to an error.

Example vcxproj producing an error:
```
...
<ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
  <ClCompile>
    ...
    <AdditionalIncludeDirectories>
      ..\foo\bar\;              <------------------------------- Line of Interest
    </AdditionalIncludeDirectories>
....
```

Error: 

> Traceback (most recent call last):
>   File "/usr/local/bin/cmake-converter", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/main.py", line 152, in main
>     convert_solution(initial_context, os.path.abspath(args.solution))
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/visual_studio/solution.py", line 278, in convert_solution
>     results = __do_conversion(initial_context, input_data_for_converter)
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/visual_studio/solution.py", line 374, in __do_conversion
>     results.append(run_conversion(data_for_converter))
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/visual_studio/solution.py", line 43, in run_conversion
>     project_data['subdirectory'],
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/visual_studio/solution.py", line 207, in convert_project
>     data_converter.convert(context)
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/data_converter.py", line 123, in convert
>     self.collect_data(context)
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/data_converter.py", line 49, in collect_data
>     context.parser.parse(context)
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/visual_studio/vcxproj/parser.py", line 113, in parse
>     self._parse_nodes(context, root)
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/parser.py", line 75, in _parse_nodes
>     node_handlers[child_node_tag](context, child_node)
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/visual_studio/vcxproj/parser.py", line 155, in __parse_item_definition_group
>     self._parse_nodes(context, node)
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/parser.py", line 75, in _parse_nodes
>     node_handlers[child_node_tag](context, child_node)
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/parser.py", line 75, in _parse_nodes
>     node_handlers[child_node_tag](context, child_node)
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/visual_studio/vcxproj/dependencies.py", line 41, in set_include_dirs
>     incl_dir.text, context.current_setting, context
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/dependencies.py", line 94, in set_additional_include_directories
>     i = normalize_path(context, working_path, i)
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/utils.py", line 412, in normalize_path
>     actual_path_name = get_actual_filename(context, joined_path)
>   File "/usr/local/lib/python3.7/site-packages/cmake_converter/utils.py", line 385, in get_actual_filename
>     test_name += ["%s[%s]" % (d[:-1], d[-1])]   <------------------------------- Line of Interest
> IndexError: string index out of range

Fix (?):

in /usr/local/lib/python3.7/site-packages/cmake_converter/utils.py

before line 385 i added
```
if dirs[-1] == '':
    del dirs[-1]
```

to remove the last directory if it is '' (entry is created because of 

`..\directory\;` instead of `..\directory;` in vcxproj)

**Comment by pavelliavonau** [comment]
@bigla , I can't reproduce this crash on Windows. Check test solution, please, and get the error with test solution and provide right test example of solution.

**Comment by bigla** [comment]
Update:
I seem to have skipped some important bits of information:
* I am working on a docker image (python:latest)
* My initial post was about converting the .sln file, now i tried with .vcxproj file, still did not work (without my fix suggestion)
* My AdditionalIncludeDirectories are semicolon-separated (works for all other subprojects), is this non-conformant with the xml-scheme?
* When removing the "\\" before the ";" e.g. changing "parentfolder\folder\\;otherfolder" to "parentfolder\folder;otherfolder" it works.

I will test your solution as soon as i can.

Example structure where my cmake-conversion fails:
```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
...
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <ClCompile>
      <Optimization>Disabled</Optimization>
      <AdditionalIncludeDirectories>folder_1\include;folder_1\include\QtCore;folder_1\include\QtGui;folder_1\include\QtXml;folder_1\include\QtWidgets;folder_2\include;folder_3;..\..\bar\;..\..\bar\common\windows;..\..\bar\commonExt\windows;..\..\bar\Communicator\windows;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
...
    </ClCompile>
    <ProjectReference>
      <UseLibraryDependencyInputs>false</UseLibraryDependencyInputs>
    </ProjectReference>
    <Link>
...
    </Link>
  </ItemDefinitionGroup>
...
</Project>
```

**Comment by bigla** [comment]
On Windows this error does not show up.

**Comment by pavelliavonau** [comment]
I closed the issue. Can you reproduce it with the latest code?

**Comment by pavelliavonau** [comment]
@bigla , is this bug actual for you?

**Comment by bigla** [comment]
@pavelliavonau i can check tomorrow, will report back.
