### ISSUE TITLE
Wrong and empty variables at TargetName section in generated CMakeLists.txt

### ISSUE THREAD

**Issue by bigla** [algorys/cmakeconverter#57]
The project I work on has a vcxproj file where
`<RootNamespace>ProjName</RootNamespace>`
and
`<TargetName>FOO</TargetName>`
and 
`<OutputFile>$(OutDir)$(TargetName)$(TargetExt)</OutputFile>`

The conversion then yields:
```
string(CONCAT TARGET_NAME
          $<$<CONFIG:Debug>:${OUT_DIR}${TARGET_NAME}$ENV{TargetExt}>
        $<$<CONFIG:Release>:${OUT_DIR}${TARGET_NAME}$ENV{TargetExt}>
        $<$<NOT:$<OR:$<CONFIG:Debug>,$<CONFIG:Release>>>:${PROJECT_NAME}>
...
set_target_properties(${PROJECT_NAME} PROPERTIES OUTPUT_NAME ${TARGET_NAME})
```

Which creates the following error in CMake:

> CMake Error at total/ProjName/CMakeLists.txt:31 (add_executable):
>   Target 'ProjName' OUTPUT_NAME depends on itself.

is this behavior expected?

(BTW. I hope I am not going on anyone's nerves, I am still new to github as well as testing/contributing to open-source projects)

**Comment by bigla** [comment]
<TargetName> is a user defined property, sure you cannot handle all of them. I closed it.

**Comment by pavelliavonau** [comment]
@bigla , it may be the bug. Must be checked.

**Comment by hamaney** [comment]
could you please elaborate on "<TargetName> is a user defined property, sure you cannot handle all of them"

Thnaks

**Comment by bigla** [comment]
> could you please elaborate on " is a user defined property, sure you cannot handle all of them"

I thought, that the tag `<TargetName>` is something my colleagues added to the .vcxproj files by using some vodoo but now, I am not sure again.
