### ISSUE TITLE
Respect `ExcludedFromBuild`?

### ISSUE THREAD

**Issue by wumo** [algorys/cmakeconverter#59]
The element `<ExcludedFromBuild>` hasn't been respected, which leads to all files are included for diffenent configuration.

**Comment by bigla** [comment]
As far as I understood, in the CMake world there is no `<ExcludeFromBuild>` equivalent at the moment. At least there won't be any visual representation like the red stop sign in MS VS. 

Besides: Some devs prefer having the non-build sources in an extra folder, some would like to have them in the same folder as the other sources/headers.

The somewhat hacky solution i chose would be to 

* add a new group of files
```
set(no_build_files__src
    non_build_file.cpp
)
```

* set the new groups' files source-file-property HEADER_FILE_ONLY to TRUE.
`set_source_files_properties(${no_build_files__src} PROPERTIES HEADER_FILE_ONLY TRUE) # To ignore during build`

* add the new group to the normal source group (so it is visible in VS under the sources folder.
```
set(Source_Files
    some_normal_source.cpp
    ${no_Build_Files__src}
)
source_group("Source Files" FILES ${Source_Files})
```

* Inform the developer of non-built files:
```
FOREACH(source_file ${no_build_files__src})
    message(STATUS "${PROJECT_NAME}: ${source_file} will not be built!")
ENDFOREACH(source_file)
```
