### ISSUE TITLE
where is cmakeconverter.py

### ISSUE THREAD

**Issue by screig** [algorys/cmakeconverter#6]
Sorry if I am missing the obvious, but where is the main script, cmakeconverter.py?

Thanks
Sean

**Comment by algorys** [comment]
@screig this file have been currently removed. I've not yet update documentation.

Simply clone project and do:

```bash
sudo pip install .
```

Then use `cmake-converter` as normal.

**Comment by screig** [comment]
thanks, got it to generate a make file, but FYI it did generate an error:

![image](https://user-images.githubusercontent.com/4292074/31939205-893d00ea-b8b1-11e7-8b14-70977fd0bcbf.png)

**Comment by algorys** [comment]
Argh :cry: I'll fix it. Please try to paste instead of image next time.

**Comment by screig** [comment]
sean@temp$ sudo cmake-converter -p 'test_native_library.vcxproj'
INFO : Project to convert = test_native_library.vcxproj
WARN : CMakeLists.txt path is not set. He will be generated in current directory.
INFO : CMakeLists will be build in current directory.
OK   : Output Debug =

OK   : Output Release =

INFO : Include Directories is not set.
INFO : No link needed.
OK   : Warning : Level3
INFO : No WholeProgramOptimization for Debug
INFO : No WholeProgramOptimization for Release
INFO : No UseDebugLibrairies for Debug
INFO : No UseDebugLibrairies for Release
INFO : No RuntimeLibrary for Debug
INFO : No RuntimeLibrary for Release
OK   : Optimization for Debug
OK   : Optimization for Release
INFO : No IntrinsicFunctions for Debug
OK   : IntrinsicFunctions for Release
INFO : No RuntimeTypeInfo for Debug
INFO : No RuntimeTypeInfo for Release
OK   : FunctionLevelLinking for release.
OK   : GenerateDebugInformation for debug.
OK   : GenerateDebugInformation for release.
OK   : ExceptionHandling for debug.
OK   : ExceptionHandling for release.
OK   : Debug   FLAGS found =  /W3 /Od /Zi /EHsc
OK   : Release FLAGS found =  /W3 /Od /Oi /Gy /Zi /EHsc
INFO : CMake will build a SHARED Library.
Traceback (most recent call last):
  File "/usr/local/bin/cmake-converter", line 9, in <module>
    load_entry_point('cmake-converter==0.0.1', 'console_scripts', 'cmake-converter')()
  File "/usr/local/lib/python3.5/dist-packages/cmake_converter-0.0.1-py3.5.egg/cmake_converter/main.py", line 102, in main
    all_data.create_data()
  File "/usr/local/lib/python3.5/dist-packages/cmake_converter-0.0.1-py3.5.egg/cmake_converter/data_converter.py", line 123, in create_data
    depends.link_dependencies()
  File "/usr/local/lib/python3.5/dist-packages/cmake_converter-0.0.1-py3.5.egg/cmake_converter/dependencies.py", line 148, in link_dependencies
    dependencies = self.tree.xpath('//ns:AdditionalDependencies', namespaces=self.ns)[0]
IndexError: list index out of range
[temp.zip](https://github.com/algorys/cmakeconverter/files/1410487/temp.zip)

**Comment by algorys** [comment]
@screig last commit should resolve this problem.

**Comment by screig** [comment]
wow that was fast! thanks

**Comment by algorys** [comment]
@screig yes but seems not work. I'll fix it ASAP.

**Comment by screig** [comment]
ok thanks, will give it a try

**Comment by screig** [comment]
no errors (great and thanks by the way!) on generating the CMakeLists.txt file, however on opening cmake:

> The CXX compiler identification is MSVC 19.12.25805.1
> Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/Preview/Community/VC/Tools/MSVC/14.12.25805/bin/Hostx86/x64/cl.exe
> Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/Preview/Community/VC/Tools/MSVC/14.12.25805/bin/Hostx86/x64/cl.exe -- works
> Detecting CXX compiler ABI info
> Detecting CXX compiler ABI info - done
> Detecting CXX compile features
> Detecting CXX compile features - done
> Build type not specified: Use Release by default.
> **You have called ADD_LIBRARY for library test_native_library without any source files. This typically indicates a problem with your CMakeLists.txt file**
> Configuring done

**Comment by algorys** [comment]
Ok I've seen where is the problem, files are beside your vcxproj, so folders variable are empty set... I'll try to find a fix.

**Comment by algorys** [comment]
@screig ok, I tested with your files and your project and it compiles perfectly :tada:

**Comment by screig** [comment]
thank you again!

**Comment by algorys** [comment]
You're welcome. Open a new issue if needed.
