### ISSUE TITLE
Wrong order of applying properties (in case of using cmake from *.props)

### ISSUE THREAD

**Issue by yrHeTaTeJlb** [algorys/cmakeconverter#61]
Sometimes it is necessary to rewrite values set by converter

**Comment by bigla** [comment]
Not intending to pollute the issue tracker, but how about starting a collection of variable mappings?

* Translating props variables to cmake:
`<WindowsTargetPlatformVersion> == ${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}`

* Translating vcxproject variables to cmake:
```
$(Configuration) == ${CMAKE_CFG_INTDIR} # info: https://cmake.org/cmake/help/v3.0/variable/CMAKE_CFG_INTDIR.html
$(Platform) == ${CMAKE_VS_PLATFORM_NAME}
```

**Comment by pavelliavonau** [comment]
@bigla, if you have proposals like this, create another issue for separate discussion, please.

**Comment by pavelliavonau** [comment]
Moving props is not enough.
Order for properties must be following:
1. Apply default values.
2. Apply values from props.
3. Apply values from project.
