### ISSUE TITLE
Keep props files order

### ISSUE THREAD

**Issue by yrHeTaTeJlb** [algorys/cmakeconverter#63]
The article [Working with Project Properties](https://docs.microsoft.com/en-us/previous-versions/669zx6zc%28v%3dvs.140%29) says:
> All the property sheets are imported automatically into the project's "master" property sheet (ms.cpp.props) and are evaluated in the order they appear in Property Manager. You can move them to change the evaluation order. Property sheets that are evaluated later will override the values in previously-evaluated sheets.

In a *.vcxproj file they are placed in the order of evaluation. But seems like cmakeconverter places them in alphabetical order.

**Comment by pavelliavonau** [comment]
2d1818ab1272e8917f76673f3226d2c3d7c2354e
