### ISSUE TITLE
Colours broken on Windows

### ISSUE THREAD

**Issue by gvanem** [algorys/cmakeconverter#66]
I just discovered this cool project; contrary to what the README says, the generated `CMakeLists.txt` actually worked for me in a plain C-project (except for a `CMAKE_VS_PLATFORM_NAME "x64"` that I replaced with `"Win32"`).

Anyway, the colours in a Windows console gives me only ANSI sequences. Like this after changing `usage =` into:
```py
from cmake_converter.utils import WARN, ENDC
usage = WARN + "cmake-converter -p <vcxproj> [-c | -a | -D | -O | -i | -std | -dry | -silent | -j]" + ENDC
```
a `cmake-converter.exe -h` gives:
```
usage: ←[33m←[1mcmake-converter -p <vcxproj> [-c | -a | -D | -O | -i | -std | -dry | -silent | -j]←[39m←[0m
```

I have no `TERM` in my environment. And `colorama` (v.0.4.1) works fine in other Python2/3 programs.

**Comment by pavelliavonau** [comment]
@gvanem, how have you installed cmake-converter?
And how have you converted your project with it(cmd line)?

**Comment by gvanem** [comment]
@pavelliavonau I installed by D/L the .zip from Github. Then a `py -3 setup.py install` which produced a 
`f:\ProgramFilerPython36\Scripts\cmake-converter.exe`. 

> And how have you converted your project with it(cmd line)?

Yes, how else. Like this `cmake-converter.exe -s envtool.sln`.
Another problem was that when it didn't find the `envtool.vcxproj`, it went wild spawning a bunch of `python.exe` sub-processes.  Even a `^C` didn't kill the process-tree. Had to use *Process Explorer* 🤒 .

**Comment by gvanem** [comment]
> Let me see the structure tree of your sln.

Does that have anything to do with broken colours?
Anyway here they are:
* http://www.watt-32.net/misc/envtool.sln 
* http://www.watt-32.net/misc/envtool.vcxproj
