### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte

### ISSUE THREAD

**Issue by Dynad** [algorys/cmakeconverter#67]
I'm trying to run with the command "cmake-converter -s F:\_CODE\Project\Project.sln" but the cmake converter returns: "ValueError: path is on mount 'C:', start on mount 'F:'".

What can I do this fix this problem?

**Comment by pavelliavonau** [comment]
What is the strange path? Are you using Windows?

**Comment by pavelliavonau** [comment]
And what about first question?

**Comment by Dynad** [comment]
The project is located on the F: drive, I don't use my C: drive for coding projects. Instead of C\:_CODE\Project\Project.sln I use F\:_CODE\Project\Project.sln.

**Comment by pavelliavonau** [comment]
"cmake-converter -s F:\_CODE\Project\Project.sln"
should work. You missed the slash after 'F:'.

**Comment by vimgaa** [comment]
i get this error when i try commend:
cmake-converter -s "H:\\GitHub\\A\\Source\\A\\A.sln"
Traceback (most recent call last):
  File "C:\Users\qwer\AppData\Local\Programs\Python\Python37-32\Scripts\cmake-converter-script.py", line 11, in <module>
    load_entry_point('cmake-converter==1.2.0', 'console_scripts', 'cmake-converter')()
  File "c:\users\qwer\appdata\local\programs\python\python37-32\lib\site-packages\cmake_converter\main.py", line 160, in main
    projects = p.findall(sln.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence

**Comment by pavelliavonau** [comment]
@vimgaa, your error has another origin - Unicode decode error. Find issue about this error and comment there, please. Also provide your or similar file to me to reproduce this problem.

**Comment by pavelliavonau** [comment]
No response.
