### ISSUE TITLE
Add support for global tag parsing and dependency resolution

### ISSUE THREAD

**Issue by chjz1024** [algorys/cmakeconverter#73]
I've been stuck in this problem for 2 days and solved them by adding or changing some outputs manually. But I think some of the difficulties I encountered should be solved by this program. Here I'll discribe the problem and how I solved it.

* Software version: 1.2.0

Directory structure:
> build
> ├── HM_vc2015.sln
> └── vc2015
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    ├── TAppCommon_vc2015.vcxproj
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    ├── TAppDecoderAnalyser_vc2015.vcxproj
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    ├── TAppDecoder_vc2015.vcxproj
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    ├── TAppEncoder_vc2015.vcxproj
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    ├── TAppMCTSExtractor_vc2015.vcxproj
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    ├── TLibCommon_vc2015.vcxproj
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    ├── TLibDecoderAnalyser_vc2015.vcxproj
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    ├── TLibDecoder_vc2015.vcxproj
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    ├── TLibEncoder_vc2015.vcxproj
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    └── TLibVideoIO_vc2015.vcxproj
* Problem1: `cmake-converter -s HM_vc2015.sln`.
  Output: 
```
0.000038 processes count = 8
0.000067 warnings level = 3


0.022168 1> Conversion started: Project TAppDecoder
0.027008 1> WARN : ('Debug', 'Win32') : file or path "/home/chjz/trunk/build/vc2015/source/Lib" not found.
0.027040 1> WARN : ('Debug', 'Win32') : getting actual filesystem name failed : "/home/chjz/trunk/build/vc2015/source/Lib"
0.027902 1> WARN : ('Debug', 'x64') : file or path "/home/chjz/trunk/build/vc2015/source/Lib" not found.
0.027922 1> WARN : ('Debug', 'x64') : getting actual filesystem name failed : "/home/chjz/trunk/build/vc2015/source/Lib"
0.028685 1> WARN : ('Release', 'Win32') : file or path "/home/chjz/trunk/build/vc2015/source/Lib" not found.
0.028704 1> WARN : ('Release', 'Win32') : getting actual filesystem name failed : "/home/chjz/trunk/build/vc2015/source/Lib"
0.029483 1> WARN : ('Release', 'x64') : file or path "/home/chjz/trunk/build/vc2015/source/Lib" not found.
0.029501 1> WARN : ('Release', 'x64') : getting actual filesystem name failed : "/home/chjz/trunk/build/vc2015/source/Lib"
```

The path in .vcxproj is `<AdditionalIncludeDirectories>$(SolutionDir)\..\source\Lib\;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>`, where `$(SolutionDir)\..\` is parsed as `${CMAKE_CURRENT_SOURCE_DIR}`, while `$(SolutionDir)` should be resolved to where HM_vc2015.sln locates. So `$(SolutionDir)\..\` should become `${CMAKE_SOURCE_DIR}\..\`.

* Problem2: After changing all the `<AdditionalIncludeDirectories />` tags manually, trying to rerun that command gives the following result:
```
0.000039 processes count = 8
0.000068 warnings level = 3


0.024898 1> Conversion started: Project TAppDecoder
0.044570 1> Conversion done   : Project TAppDecoder
0.045787 2> Conversion started: Project TAppEncoder
0.062011 2> Conversion done   : Project TAppEncoder
0.062827 3> Conversion started: Project TAppCommon
0.065861 3> WARN : ('Debug', 'Win32') : Unknown variable: $(RootNamespace), trying $ENV{RootNamespace}
0.065955 3> WARN : ('Debug', 'x64') : Unknown variable: $(RootNamespace), trying $ENV{RootNamespace}
0.066034 3> WARN : ('Release', 'Win32') : Unknown variable: $(RootNamespace), trying $ENV{RootNamespace}
0.066111 3> WARN : ('Release', 'x64') : Unknown variable: $(RootNamespace), trying $ENV{RootNamespace}
```
Here is where `$(RootNamespace)` locates in TAppCommon_vc2015.vcxproj:
```
  <PropertyGroup Label="Globals">
    <ProjectName>TAppCommon</ProjectName>
    <ProjectGuid>{D1E8A1C2-15DB-4C94-80E8-4F70CF0A2DC5}</ProjectGuid>
    <RootNamespace>TAppCommon</RootNamespace>
    <Keyword>Win32Proj</Keyword>
  </PropertyGroup>
```
I changed all the `$ENV{RootNamespace}` to get a right CMakeLists.txt.

* Problem 3: This problem is related to dependency resolution. Everytime I tried to build the project, there are always messages of `undefined reference`. After checking all the functions not defined, I found all of them come from project TLibCommon.
In the original .vcxproj file, dependencies are defined as follows:
```
  <ItemGroup>
    <ProjectReference Include="TAppCommon_vc2015.vcxproj">
      <Project>{d1e8a1c2-15db-4c94-80e8-4f70cf0a2dc5}</Project>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
    <ProjectReference Include="TLibCommon_vc2015.vcxproj">
      <Project>{78018d78-f890-47e3-a0b7-09d273f0b11d}</Project>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
    <ProjectReference Include="TLibEncoder_vc2015.vcxproj">
      <Project>{47e90995-1fc5-4ee4-a94d-ad474169f0e1}</Project>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
    <ProjectReference Include="TLibVideoIO_vc2015.vcxproj">
      <Project>{5280c25a-d316-4be7-ae50-29d72108624f}</Project>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
```
and the corresponding cmake commands are:
```
################################################################################
# Dependencies
################################################################################
add_dependencies(${PROJECT_NAME}
    TAppCommon
    TLibCommon
    TLibEncoder
    TLibVideoIO
)

# Link with other targets.
target_link_libraries(${PROJECT_NAME} PUBLIC
    TAppCommon
    TLibCommon
    TLibEncoder
    TLibVideoIO
)
```
TLibEncoder_vc2015.vcxproj and TLibDecoder_vc2015.vcxproj don't have the `<ProjectReference />` tag.

After examining carefully (1 day), I found that problem can be solved by adding `target_link_libraries` to the corresponding project section (TLibEncoder and TLibDecoder only generate static libraries).

I think this problem is relatively hard to solve and need some help from experts of Visual Studio.

The source code is in [https://hevc.hhi.fraunhofer.de/](https://hevc.hhi.fraunhofer.de/) and the corrected version is in [https://github.com/chjz1024/HM_vc2015](https://github.com/chjz1024/HM_vc2015).

**Comment by pavelliavonau** [comment]
@chjz1024, 
I can't reproduce problem number 1. Try it with latest code.
Problem number 2 - fixed.
if you have any new input about problem 3 - give, please.

Special thanks for the best clarification)

**Comment by chjz1024** [comment]
@pavelliavonau ,
Thank you for your quick response.

I still have the same problem 1 after updating the code.
If you used my HM_vc2015 repository for test, then it won't throw any error message because I have changed all the .vcxproj files. The source code is subversioned at [https://hevc.hhi.fraunhofer.de/svn/svn_HEVCSoftware/trunk/](https://hevc.hhi.fraunhofer.de/svn/svn_HEVCSoftware/trunk/) or you could just revert the changes I have made in my repository.

For linkage error, yes you are right. I use GCC 7.3.0 for compilation and solved this problem by simply changing the order in target_link_libraries, from
```
################################################################################
# Dependencies
################################################################################
add_dependencies(${PROJECT_NAME}
    TAppCommon
    TLibCommon
    TLibEncoder
    TLibVideoIO
)

# Link with other targets.
target_link_libraries(${PROJECT_NAME} PUBLIC
    TAppCommon
    TLibCommon
    TLibEncoder
    TLibVideoIO
)
```
to
```
################################################################################
# Dependencies
################################################################################
add_dependencies(${PROJECT_NAME}
    TAppCommon
    TLibEncoder
    TLibVideoIO
    TLibCommon
)

# Link with other targets.
target_link_libraries(${PROJECT_NAME} PUBLIC
    TAppCommon
    TLibEncoder
    TLibVideoIO
    TLibCommon
)
```
So that's something related to gcc. Well I don't know if that would be solved in the future release:sweat_smile:.

**Comment by pavelliavonau** [comment]
It's not a bug. ld has another algorithm for linking than link.exe.
Correct scripts for gcc is not an aim of this project. That's why I almost don't care about gcc errors at this code. 
I suppose that you can convert once and then fix it for gcc if you want.
