### ISSUE TITLE
Invalid project path from solution like "..\Source\project.vcxproj"

### ISSUE THREAD

**Issue by SergeiDelov** [algorys/cmakeconverter#74]
Using .sln file as input: 
Converter tries to open invalid path when project path in solution starts from "..", like "..\Source\Model\Model_123"

WARN : ('Debug', 'x64') : file or path "D:\projects\Engine\Solution..\Source\Model\Model_123" not found.

I guess valid file name should be formed as D:\projects\Engine\Solution\..\Source\Model\Model_123.

**Comment by pavelliavonau** [comment]
I've tried next:
`Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "StaticLibStub", "..\StaticLibStub\StaticLibStub.vcxproj", "{8F2C2EFB-E93C-4E62-A2C4-93DEAA170B3E}"
EndProject`
Works fine for me. Provide your example, please.

**Comment by SergeiDelov** [comment]
Debugging.
That's what I see:

Exception:

path is on mount 'C:', start on mount 'D:'

Stack trace:
 >  File "D:\projects\cmake_converter\cmake_converter\main.py", line 113,
in main
 >    convert_solution(initial_context, os.path.abspath(args.solution))
 >  File "D:\projects\cmake_converter\cmake_converter\main.py", line 117,
in <module>
 >    main()

**Comment by SergeiDelov** [comment]
...

 File "C:\Program
Files\Python37\lib\site-packages\cmake_converter\dependencies.py", line 97,
in set_additional_include_directories
    i = normalize_path(context, working_path, i)
  File "C:\Program
Files\Python37\lib\site-packages\cmake_converter\utils.py", line 589, in
normalize_path
    normal_path = set_unix_slash(os.path.relpath(actual_path_name,
working_path))
  File "C:\Program Files\Python37\lib\ntpath.py", line 562, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'C:', start on mount 'D:'

**Comment by pavelliavonau** [comment]
I can't understand what was happened.
Attach full log with verbose mode and stacktrace. Also provide your filesystem tree of sln and projects.
