### ISSUE TITLE
No settings when solution and project arch differs (x86 and Win32 for example)

### ISSUE THREAD

**Issue by goodandrewsoft** [algorys/cmakeconverter#76]
> Note : Actually, it's only works with C/C++ (*.vcxproj) and Fortran (*.vfproj) projects.

and

> After install library, just run the script as below. Your *.sln file is of course required: cmake-converter -s <path/to/file.sln>

How convert http://www.ucancode.net/Visual_C_Source_Code/multimon_demo.zip ?

**Comment by pavelliavonau** [comment]
@goodandrewsoft ,
So, first you must upgrade your solution to mor erecent version with visual studio. 
`Microsoft Visual Studio Solution File, Format Version 8.00` 
is not supported.
Then I found bug with different arch names and fixed it. Now your project converted well on my side.
Any objections?

**Comment by goodandrewsoft** [comment]
I don't have Visual Studio

**Comment by pavelliavonau** [comment]
Why? You may use Community Edition.
You may try to convert manually.

Anyway, I can't support all versions of solutions.

**Comment by goodandrewsoft** [comment]
Because i don't want install Visual Studio just for convert projects.

**Comment by pavelliavonau** [comment]
Maybe you don't want to convert projects enough.
You may ask somebody then.
I can't help in this case.

**Comment by goodandrewsoft** [comment]
Ну на нет и суда нет.
