### ISSUE TITLE
Error when certain tags are not in vcxproj file

### ISSUE THREAD

**Issue by ferria** [algorys/cmakeconverter#8]
Thanks for making this.  I tried to run it and noticed errors when trying to run [this](https://github.com/Synodic-Software/Soul-Engine/blob/dev/Build/Soul%20Engine.vcxproj) file on the lines when tree.xpath(...)[0] is called for 'WarningLevel' and 'PreprocessorDefinitions'.

**Comment by algorys** [comment]
Done.
